<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GiayTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('giay')->delete();
        
        \DB::table('giay')->insert(array (
            0 => 
            array (
                'id_giay' => 1,
                'ten_giay' => 'NMD R2',
                'ten_loai_giay' => 'Sandanl',
                'ten_thuong_hieu' => 'Gucci',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '1200000',
                'so_luong' => '78',
                'hinh_anh_1' => 'giay13.jpg',
                'hinh_anh_2' => 'giay13.jpg',
                'hinh_anh_3' => 'giay13.jpg',
                'hinh_anh_4' => 'giay13.jpg',
                'ten_khuyen_mai' => 'Ngày lễ',
                'so_luong_mua' => '23',
                'created_at' => '2021-11-25 14:59:26',
                'updated_at' => '2025-11-15 10:39:50',
            ),
            1 => 
            array (
                'id_giay' => 2,
                'ten_giay' => 'Nike Joma IC',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Nike',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '666000',
                'so_luong' => '96',
                'hinh_anh_1' => 'giay4.jpg',
                'hinh_anh_2' => 'giay4.jpg',
                'hinh_anh_3' => 'giay4.jpg',
                'hinh_anh_4' => 'giay4.jpg',
                'ten_khuyen_mai' => 'Mới ra mắt',
                'so_luong_mua' => '4',
                'created_at' => '2021-11-29 14:59:26',
                'updated_at' => '2025-11-15 10:41:58',
            ),
            2 => 
            array (
                'id_giay' => 3,
                'ten_giay' => 'The Nike Premier II',
                'ten_loai_giay' => 'Sneaker',
                'ten_thuong_hieu' => 'Nike',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '999000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay3.jpg',
                'hinh_anh_2' => 'giay3.jpg',
                'hinh_anh_3' => 'giay3.jpg',
                'hinh_anh_4' => 'giay3.jpg',
                'ten_khuyen_mai' => 'Ngày lễ',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            3 => 
            array (
                'id_giay' => 4,
                'ten_giay' => 'Adidas PUREBOOST 21',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Adidas',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '1590000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay20.jpg',
                'hinh_anh_2' => 'giay20.jpg',
                'hinh_anh_3' => 'giay20.jpg',
                'hinh_anh_4' => 'giay20.jpg',
                'ten_khuyen_mai' => 'Mới ra mắt',
                'so_luong_mua' => '1',
                'created_at' => '2021-11-29 14:59:26',
                'updated_at' => '2025-11-13 17:41:07',
            ),
            4 => 
            array (
                'id_giay' => 5,
                'ten_giay' => 'Adidas STAN SMITH',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Adidas',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '1290000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay21.jpg',
                'hinh_anh_2' => 'giay21.jpg',
                'hinh_anh_3' => 'giay21.jpg',
                'hinh_anh_4' => 'giay21.jpg',
                'ten_khuyen_mai' => 'Mới ra mắt',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            5 => 
            array (
                'id_giay' => 6,
                'ten_giay' => 'Adidas ALPHAMAGMA',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Adidas',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '799000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay22.jpg',
                'hinh_anh_2' => 'giay22.jpg',
                'hinh_anh_3' => 'giay22.jpg',
                'hinh_anh_4' => 'giay22.jpg',
                'ten_khuyen_mai' => 'Mới ra mắt',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            6 => 
            array (
                'id_giay' => 7,
                'ten_giay' => 'Adidas RUNFALCON 2.0',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Adidas',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '599000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay23.jpg',
                'hinh_anh_2' => 'giay23.jpg',
                'hinh_anh_3' => 'giay23.jpg',
                'hinh_anh_4' => 'giay23.jpg',
                'ten_khuyen_mai' => 'Mới ra mắt',
                'so_luong_mua' => '0',
                'created_at' => '2021-11-29 14:59:26',
                'updated_at' => '2021-11-29 14:59:26',
            ),
            7 => 
            array (
                'id_giay' => 8,
                'ten_giay' => 'Adidas Tiempo Legend 9',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Adidas',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '666000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay2.jpg',
                'hinh_anh_2' => 'giay2.jpg',
                'hinh_anh_3' => 'giay2.jpg',
                'hinh_anh_4' => 'giay2.jpg',
                'ten_khuyen_mai' => 'Ngày lễ',
                'so_luong_mua' => '0',
                'created_at' => '2021-11-29 14:59:26',
                'updated_at' => '2021-11-29 14:59:26',
            ),
            8 => 
            array (
                'id_giay' => 9,
                'ten_giay' => 'Puma One 5.3 TT',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Puma',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '699000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay7.jpg',
                'hinh_anh_2' => 'giay7.jpg',
                'hinh_anh_3' => 'giay7.jpg',
                'hinh_anh_4' => 'giay7.jpg',
                'ten_khuyen_mai' => 'Sale cuối năm',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            9 => 
            array (
                'id_giay' => 10,
                'ten_giay' => 'CNVR-WZ87_V1',
                'ten_loai_giay' => 'Sneaker',
                'ten_thuong_hieu' => 'Converse',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '699000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay16.jpg',
                'hinh_anh_2' => 'giay16.jpg',
                'hinh_anh_3' => 'giay16.jpg',
                'hinh_anh_4' => 'giay16.jpg',
                'ten_khuyen_mai' => 'Không khuyễn mãi',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            10 => 
            array (
                'id_giay' => 11,
                'ten_giay' => 'Run Star Hike Sneaker',
                'ten_loai_giay' => 'Sneaker',
                'ten_thuong_hieu' => 'Converse',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '966000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay17.jpg',
                'hinh_anh_2' => 'giay17.jpg',
                'hinh_anh_3' => 'giay17.jpg',
                'hinh_anh_4' => 'giay17.jpg',
                'ten_khuyen_mai' => 'Chủ vui nên khuyến mãi',
                'so_luong_mua' => '0',
                'created_at' => '2021-11-29 14:59:26',
                'updated_at' => '2021-11-29 14:59:26',
            ),
            11 => 
            array (
                'id_giay' => 12,
                'ten_giay' => 'Chuck 70 Sneaker',
                'ten_loai_giay' => 'Sneaker',
                'ten_thuong_hieu' => 'Converse',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '1280000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay18.jpg',
                'hinh_anh_2' => 'giay18.jpg',
                'hinh_anh_3' => 'giay18.jpg',
                'hinh_anh_4' => 'giay18.jpg',
                'ten_khuyen_mai' => 'Sale cuối năm',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            12 => 
            array (
                'id_giay' => 13,
                'ten_giay' => 'Archive Paint Splatter',
                'ten_loai_giay' => 'Sneaker',
                'ten_thuong_hieu' => 'Converse',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '1880000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay19.jpg',
                'hinh_anh_2' => 'giay19.jpg',
                'hinh_anh_3' => 'giay19.jpg',
                'hinh_anh_4' => 'giay19.jpg',
                'ten_khuyen_mai' => 'Không khuyễn mãi',
                'so_luong_mua' => '0',
                'created_at' => '2021-11-29 14:59:26',
                'updated_at' => '2021-11-29 14:59:26',
            ),
            13 => 
            array (
                'id_giay' => 14,
                'ten_giay' => 'Nike Top Sala14',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Nike',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '666000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay9.jpg',
                'hinh_anh_2' => 'giay9.jpg',
                'hinh_anh_3' => 'giay9.jpg',
                'hinh_anh_4' => 'giay9.jpg',
                'ten_khuyen_mai' => 'Không khuyễn mãi',
                'so_luong_mua' => '0',
                'created_at' => '2021-11-25 14:59:26',
                'updated_at' => '2021-11-25 14:59:26',
            ),
            14 => 
            array (
                'id_giay' => 15,
                'ten_giay' => 'Nike ACE Tango',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Nike',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '599000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay6.jpg',
                'hinh_anh_2' => 'giay6.jpg',
                'hinh_anh_3' => 'giay6.jpg',
                'hinh_anh_4' => 'giay6.jpg',
                'ten_khuyen_mai' => 'Mới ra mắt',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            15 => 
            array (
                'id_giay' => 16,
                'ten_giay' => 'Adidas Mercurial',
                'ten_loai_giay' => 'Sandanl',
                'ten_thuong_hieu' => 'Adidas',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '666000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay15.jpg',
                'hinh_anh_2' => 'giay15.jpg',
                'hinh_anh_3' => 'giay15.jpg',
                'hinh_anh_4' => 'giay15.jpg',
                'ten_khuyen_mai' => 'Ngày lễ',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            16 => 
            array (
                'id_giay' => 17,
                'ten_giay' => 'Nike FC',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Nike',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '1100000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay8.jpg',
                'hinh_anh_2' => 'giay8.jpg',
                'hinh_anh_3' => 'giay8.jpg',
                'hinh_anh_4' => 'giay8.jpg',
                'ten_khuyen_mai' => 'Ngày lễ',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            17 => 
            array (
                'id_giay' => 18,
                'ten_giay' => 'Adidas X Tango 17.1 FG',
                'ten_loai_giay' => 'Sneaker',
                'ten_thuong_hieu' => 'Adidas',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '666000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay5.jpg',
                'hinh_anh_2' => 'giay5.jpg',
                'hinh_anh_3' => 'giay5.jpg',
                'hinh_anh_4' => 'giay5.jpg',
                'ten_khuyen_mai' => 'Không khuyễn mãi',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            18 => 
            array (
                'id_giay' => 19,
                'ten_giay' => 'Superstar KB',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Vans',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '1350000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay10.jpg',
                'hinh_anh_2' => 'giay10.jpg',
                'hinh_anh_3' => 'giay10.jpg',
                'hinh_anh_4' => 'giay10.jpg',
                'ten_khuyen_mai' => 'Sale cuối năm',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            19 => 
            array (
                'id_giay' => 20,
                'ten_giay' => 'Superstar J',
                'ten_loai_giay' => 'Sandanl',
                'ten_thuong_hieu' => 'Vans',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '1290000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay11.jpg',
                'hinh_anh_2' => 'giay11.jpg',
                'hinh_anh_3' => 'giay11.jpg',
                'hinh_anh_4' => 'giay11.jpg',
                'ten_khuyen_mai' => 'Ngày lễ',
                'so_luong_mua' => '0',
                'created_at' => '2021-11-25 14:59:26',
                'updated_at' => '2021-11-25 14:59:26',
            ),
            20 => 
            array (
                'id_giay' => 21,
                'ten_giay' => 'Nike Tiempo Legend',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Nike',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '1990000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay4.jpg',
                'hinh_anh_2' => 'giay4.jpg',
                'hinh_anh_3' => 'giay4.jpg',
                'hinh_anh_4' => 'giay4.jpg',
                'ten_khuyen_mai' => 'Ngày lễ',
                'so_luong_mua' => '0',
                'created_at' => '2021-11-24 14:59:26',
                'updated_at' => '2021-11-24 14:59:26',
            ),
            21 => 
            array (
                'id_giay' => 22,
                'ten_giay' => 'ADIDAS X Speedflow',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'Adidas',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '666000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay12.jpg',
                'hinh_anh_2' => 'giay12.jpg',
                'hinh_anh_3' => 'giay12.jpg',
                'hinh_anh_4' => 'giay12.jpg',
                'ten_khuyen_mai' => 'Sale cuối năm',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            22 => 
            array (
                'id_giay' => 23,
                'ten_giay' => 'Jung 96',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'New Balance',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '899000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay14.jpg',
                'hinh_anh_2' => 'giay14.jpg',
                'hinh_anh_3' => 'giay14.jpg',
                'hinh_anh_4' => 'giay14.jpg',
                'ten_khuyen_mai' => 'Sale cuối năm',
                'so_luong_mua' => '0',
                'created_at' => '2021-12-01 17:21:31',
                'updated_at' => '2021-12-01 17:21:31',
            ),
            23 => 
            array (
                'id_giay' => 24,
                'ten_giay' => 'Mercurial Superfly',
                'ten_loai_giay' => 'Sneaker',
                'ten_thuong_hieu' => 'Balenciaga',
                'mo_ta' => '<p>✔️ Đế giày được thiết kế chịu ma sát tốt, tăng chiều cao, nhẹ, êm, cân bằng và thoáng khí.&nbsp;</p><p>✔️ Kiểu dáng hottrend của năm nay.&nbsp;</p><p>✔️ Giày đẹp, nhẹ, bền. Có thể làm giày cặp, giày nhóm. Thích hợp đi chơi, chạy bộ, gym, đi học, đi làm...&nbsp;</p><p>✔️ Đế cao su bền chắc, có độ bám cao.</p><p>✔️ Mẫu mới nhất hiện nay mang êm chân thời trang cá tính.&nbsp;</p><p>✔️ Dễ dàng kết hợp với hầu hết các phong cách thời trang như: đi học, đi chơi, đi du lịch. Giày đôi, giày nhóm...</p><p>✔️ Có thể kết hợp với váy, jeans, sooc…. Đều phù hợp!!&nbsp;</p>',
                'don_gia' => '666000',
                'so_luong' => '100',
                'hinh_anh_1' => 'giay6.jpg',
                'hinh_anh_2' => 'giay6.jpg',
                'hinh_anh_3' => 'giay6.jpg',
                'hinh_anh_4' => 'giay6.jpg',
                'ten_khuyen_mai' => 'Chủ vui nên khuyến mãi',
                'so_luong_mua' => '0',
                'created_at' => '2021-11-24 14:59:26',
                'updated_at' => '2021-11-24 14:59:26',
            ),
            24 => 
            array (
                'id_giay' => 25,
                'ten_giay' => 'Giay Vip',
                'ten_loai_giay' => 'Thể thao',
                'ten_thuong_hieu' => 'VietNam',
                'mo_ta' => '<p>Giày này xịn</p>',
                'don_gia' => '999000',
                'so_luong' => '100',
                'hinh_anh_1' => 'top-15-thuong-hieu-giay-viet-nam-noi-tieng-ban-chay-nhat-h9.jpg',
                'hinh_anh_2' => 'top-15-thuong-hieu-giay-viet-nam-noi-tieng-ban-chay-nhat-h9.jpg',
                'hinh_anh_3' => 'top-15-thuong-hieu-giay-viet-nam-noi-tieng-ban-chay-nhat-h9.jpg',
                'hinh_anh_4' => 'top-15-thuong-hieu-giay-viet-nam-noi-tieng-ban-chay-nhat-h9.jpg',
                'ten_khuyen_mai' => 'Không khuyễn mãi',
                'so_luong_mua' => '0',
                'created_at' => '2025-11-14 00:24:29',
                'updated_at' => '2025-11-14 00:24:29',
            ),
        ));
        
        
    }
}